# Configuracion para H2 (Base de datos en archivo)
spring.datasource.url=jdbc:h2:file:./data/onepiece-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para que puedas ver la consola de la base de datos en el navegador
spring.h2.console.enabled=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
